name: Build TWRP Recovery

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Branch'
        required: true
        default: 'twrp-12.1'
        type: choice
        options:
          - twrp-12.1
          - twrp-13.0
          - twrp-14.1

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240
    env:
      # ГЛАВНОЕ: отключаем все токены на уровне job
      GITHUB_TOKEN: ""
      GITHUB_ACTIONS_TOKEN: ""
    
    steps:
    - name: Checkout Device Tree
      uses: actions/checkout@v4
      with:
        persist-
